### ISSUE TITLE
Console Log Spam

### ISSUE THREAD

**Issue by JuicyCosmos** [Xratedjunior/Better-Default-Biomes#25] opened 2021-08-18 14:09 UTC
Hi mod author! I've been using this mod for a long time and I absolutely love it! But recently after some crash debugging (which was caused by updating Optifine and Citadel), I found, in the game log, that BDB is spamming "Add Tree X to Biome Y". It seems that the game's running out of ids? I'm not sure why. I play with neither byg nor bop so I don't believe biome id is a problem here.
I can't tell if the issue is on BDB's side since I'm running too many mods at once but I thought I'd just open an issue here. The bug does not appear to interfere with gameplay but it's a little annoying in the console. Anywayz, thank you for your great work.
Here's the spam message that's repeated countless times in the console log:
<img width="622" alt="console_log_spam" src="https://user-images.githubusercontent.com/79921098/129912946-36d2bd99-06f9-4655-b905-a4eae166f909.PNG">

**Comment by JuicyCosmos** [comment] 2021-08-18 14:11
Oh btw I forgot to mention, mod version is alpha 2.5.3 and forge is 36.2.0, playing on Minecraft 1.16.5, all other mods in the screenshot are in their latest version for 1.16.5.

**Comment by FearlessFloyd** [comment] 2021-08-28 22:47
Same issues experienced here for days - have tried swapping out as well as removing several different biome mods and most of my world generating mods. However, issue occurred without betterdefaultbiomes installed as well, but BDB adds a lot more spam when it occurs because of the visible tree adding. ANY ideas or assistance what could be causing this in this latest batch of mod updates would be a huge help, as Blame and similar logging efforts only seem to point to different mods as I troubleshooted by taking out mods in groups at a time. I was able to rule out mods as the cause only to have it tell me the when I put them back in and pull a different mod instead. This is more than just a nuisance in the log to me as it seems to create a lag spike whenever it occurs and it can be replicated 100% of the time by doing a /save-all in addition to random occurrences. (This seems a worldgen related error and happens on server prior to clients connecting, so optifine plays no role.)

Anyone with any insight would be a help! 

[modlist.txt](https://github.com/Xratedjunior/Better-Default-Biomes/files/7071601/modlist.txt)
 
[worldsettingsimport-error.txt](https://github.com/Xratedjunior/Better-Default-Biomes/files/7071590/worldsettingsimport-error.txt)

**Comment by Xratedjunior** [comment] 2021-08-29 08:31
Firstly my apologies to @JuicyCosmos for not responding in such a long time. I thought I did, but we can all see I didn't... whoops.

The console spam will be fixed in the next update. It's annoying, but shouldn't give problems. 

The error is most likely because of another mod, because otherwise I would expect the error to occur after every generation entry for the trees.

**Comment by Xratedjunior** [comment] 2021-08-29 08:35
And @FearlessFloyd I'm reworking the way BDB generation is registered, but even in the public version the trees should only be added during world loading. 

You're saying you're experiencing the spam even while already playing?

**Comment by LordBoos** [comment] 2021-08-30 01:05
Actually this is not really a bug in your mod. Mod Infernal Expansion 2.2.0 causes this issue as it is somehow messing with world generator every 5 minutes. It is a known bug there, see https://github.com/infernalexp/Infernal-Expansion/issues/261

**Comment by JuicyCosmos** [comment] 2021-08-30 04:41
Ok so Infernal Expansion devs pushed a new update trying to resolve the issue. I'll give it a shot and see if it's actually fixed (it's reportedly fixed).

In the meanwhile, thanks everybody for providing the info and esp @Xratedjunior for working out the bugfixes!! And yes, the log was being constantly spammed during normal gameplay but as @LordBoos has pointed out this might just be a problem with Infernal Expansion, which is also included in my pack

**Closed as completed** 2022-03-30 17:51 UTC
Labels: bug
