### ISSUE TITLE
Server crash 1.20.1-Alpha 5.1.1

### ISSUE THREAD

**Issue by Illest8** [Xratedjunior/Better-Default-Biomes#37] opened 2023-12-05 05:33 UTC
https://pastebin.com/tPSQ3Jey

**Comment by Xratedjunior** [comment] 2023-12-05 07:49
Weird, should be fixed in the latest update. Let me know, because I am not able to reproduce it.

**Comment by Xratedjunior** [comment] 2023-12-05 07:50
For now I will close this as fixed. Be sure to reopen if it happens again

**Closed as completed by Xratedjunior** 2023-12-05 07:50 UTC
Labels: bug
