### ISSUE TITLE
Smelting touch not working with FTB ultimine

### ISSUE THREAD

**Issue by ItsBapo** [Xratedjunior/Better-Default-Biomes#33] opened 2023-03-12 19:04 UTC
The smelting touch enchant does not work when using the vein mine from FTB ultimine. The enchant works when normally mining the blocks 1 by 1.

**Comment by Xratedjunior** [comment] 2023-12-05 07:49
Whoops, I meant #37

**Comment by Xratedjunior** [comment] 2023-12-05 07:54
Closed, because duplicate of #12

**Closed as completed** 2023-12-05 07:54 UTC
Labels: bug, duplicate
